name: Compile

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  go-compile-check:
    name: "Run compilation check on  Go files"
    needs: go-lint
    strategy:
      matrix:
        os: ["macos", "ubuntu", "windows"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -v ./...
