# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Go Release"

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
        os: ["windows", "linux", "darwin", "freebsd"]
        exclude:
          - os: "darwin"
            arch: "386"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"

    - name: Build
      run: |
        mkdir bin
        go build -v --ldflags="${LDFLAGS}" -o bin ./...
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        LDFLAGS: "-w -s -X 'main.version=${{ github.ref_name }}'"

    - name: "Zip exe files"
      if: ${{ matrix.os == 'windows' }}
      run: |
        cd bin
        zip "spawn-${{ matrix.os }}-${{ matrix.arch }}.zip" spawn.exe
        rm spawn.exe

    - name: "Tarball binaries"
      if: ${{ matrix.os != 'windows' }}
      run: |
        cd bin
        tar czf "spawn-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" spawn
        rm spawn

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: "spawn-${{ matrix.os }}-${{ matrix. arch }}"
        path: bin

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: "Download Artifacts"
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}

    - name: "Flatten Folders"
      run: |
        mv **/* .
        find -mindepth 1 -maxdepth 1 -type d -exec rmdir {} \;
        ls -al .
    
    - name: Checksum
      run: |
        find . -type f -exec sha256sum {} > sha256sums.txt \;
        cat sha256sums.txt

    - name: "Create Release"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generate_release_notes: true
        files: ./*
