# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"

    - name: Build
      run: go build -v --ldflags="${LDFLAGS}" ./...
      env:
        BIN_VERSION: "$(git rev-parse --short HEAD)"
        LDFLAGS: "-X 'main.version=${BIN_VERSION}'"
        GOBIN: "$(pwd)/bin"

    - name: "Create Release"
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release {tag}"
        draft: false
        file: "spawn"
        prerelease: false
